# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-01 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),

                ('state', django_fsm.FSMField(choices=[(b'APPROVED', b'APPROVED'), (b'DELETED', b'DELETED'), (b'DRAFT', b'DRAFT'), (b'EXPIRED', b'EXPIRED'), (b'FOR_MODERATORS', b'FOR_MODERATORS'), (b'PUBLISHED', b'PUBLISHED'), (b'REJECTED', b'REJECTED')], default=b'DRAFT', max_length=50, protected=True, verbose_name=b'Publication State')),
                ('display_from', models.DateTimeField(blank=True, null=True)),
                ('display_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
    ]
